### ISSUE TITLE
v0.98.1-118-g309f-dirty keeps crashing

### ISSUE THREAD

**Issue by phixion** [AdguardTeam/AdGuardHome#1031]
- [x ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * v0.98.1-118-g309f-dirty
* **How did you setup DNS configuration:**
  * IoT
* **If it's a router or IoT, please write device model:**
  * rpi 3b
* **Operating system and version:**
  * archlinux-arm

### Expected Behavior
service runs

### Actual Behavior
service crashes

### Screenshots
```
[root@omega adguard]# ./AdGuardHome
2019/09/28 20:22:56 [info] AdGuard Home, version v0.98.1-118-g309f-dirty, channel beta

2019/09/28 20:22:56 [info] Added 20 client aliases from /etc/hosts
2019/09/28 20:22:57 [info] Upstream 0: 127.0.0.1:5555
2019/09/28 20:22:57 [info] Upstream 1: 127.0.0.1:5555
2019/09/28 20:22:57 [info] Upstream 2: 10.10.10.1:53 is reserved for next domains: internal.phixion.org.
2019/09/28 20:22:57 [info] Upstream 3: 10.10.15.1:53 is reserved for next domains: guest.internal.phixion.org.
2019/09/28 20:22:57 [info] Starting the DNS proxy server
2019/09/28 20:22:57 [info] Ratelimit is enabled and set to 20 rps
2019/09/28 20:22:57 [info] The server is configured to refuse ANY requests
2019/09/28 20:22:57 [info] DNS cache is enabled
2019/09/28 20:22:57 [info] Creating the UDP server socket
2019/09/28 20:22:57 [info] Listening to udp://[::]:53
2019/09/28 20:22:57 [info] Creating the TCP server socket
2019/09/28 20:22:57 [info] Listening to tcp://[::]:53
2019/09/28 20:22:57 [info] Creating the TLS server socket
2019/09/28 20:22:57 [info] Listening to tls://[::]:853
2019/09/28 20:22:57 [info] Entering the tls listener loop on [::]:853
2019/09/28 20:22:57 [info] AdGuard Home is available on the following addresses:
2019/09/28 20:22:57 [info] Go to http://127.0.0.1:80
2019/09/28 20:22:57 [info] Go to http://10.10.10.10:80
2019/09/28 20:22:57 [info] Entering the tcp listener loop on [::]:53
2019/09/28 20:22:57 [info] Entering the UDP listener loop on [::]:53
2019/09/28 20:22:57 [info] number of certs - 2
2019/09/28 20:22:57 [info] got an intermediate cert
2019/09/28 20:22:58 [info] Go to https://omega.internal.phixion.org
2019/09/28 20:23:07 [info] Filter 1569360370 has been updated: 413436 bytes, 14551 rules
2019/09/28 20:23:15 [info] Filter 1569360379 has been updated: 745878 bytes, 26387 rules
2019/09/28 20:23:15 [info] Added 2 client aliases from 'arp -a' command output
2019/09/28 20:23:17 [info] Filter 1569360384 has been updated: 37887 bytes, 1526 rules
2019/09/28 20:23:19 [info] Filter 1569360385 has been updated: 1210467 bytes, 65470 rules
panic: runtime error: slice bounds out of range

goroutine 13 [running]:
github.com/AdguardTeam/AdGuardHome/home.(*filter).update(0x1409aa4, 0x1409a00, 0x0, 0x0)
        /opt/atlassian/application-data/bamboo/xml-data/build-dir/1933313/AGH-AGHBETA-JOB1/home/filter.go:373 +0xa3c
github.com/AdguardTeam/AdGuardHome/home.refreshFiltersIfNecessary(0x0, 0x0)
        /opt/atlassian/application-data/bamboo/xml-data/build-dir/1933313/AGH-AGHBETA-JOB1/home/filter.go:235 +0x3c8
github.com/AdguardTeam/AdGuardHome/home.startRefreshFilters.func1()
        /opt/atlassian/application-data/bamboo/xml-data/build-dir/1933313/AGH-AGHBETA-JOB1/home/filter.go:32 +0x1c
created by github.com/AdguardTeam/AdGuardHome/home.startRefreshFilters
        /opt/atlassian/application-data/bamboo/xml-data/build-dir/1933313/AGH-AGHBETA-JOB1/home/filter.go:31 +0x24
[root@omega adguard]#

```

</details>

**Comment by Eyeborgs** [comment]
#1028
