### ISSUE TITLE
[beta] invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by bestpika** [AdguardTeam/AdGuardHome#1555]
### Issue Details

- Install as service

```
C:\AdGuardHome>AdGuardHome.exe -s install
2020/04/08 00:03:35 [info] Service control action: install
2020/04/08 00:03:35 [info] Service has been started
2020/04/08 00:03:35 [info] Almost ready!
AdGuard Home is successfully installed and will automatically start on boot.
There are a few more things that must be configured before you can use it.
Click on the link below and follow the Installation Wizard steps to finish setup.
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x7fab99]

goroutine 1 [running]:
github.com/AdguardTeam/AdGuardHome/home.(*TLSMod).WriteDiskConfig(0x0, 0x12d03dc8)
        /builder/1/bamboo-agent-home/xml-data/build-dir/AGH-AGHBETA-JOB1/home/tls.go:70 +0x19
github.com/AdguardTeam/AdGuardHome/home.printHTTPAddresses(0x8d4222, 0x4)
        /builder/1/bamboo-agent-home/xml-data/build-dir/AGH-AGHBETA-JOB1/home/home.go:569 +0x4a
github.com/AdguardTeam/AdGuardHome/home.handleServiceInstallCommand(0xbc62e0, 0x12cf8100)
        /builder/1/bamboo-agent-home/xml-data/build-dir/AGH-AGHBETA-JOB1/home/service.go:220 +0x13e
github.com/AdguardTeam/AdGuardHome/home.handleServiceControlAction(0x12c940a0, 0x7)
        /builder/1/bamboo-agent-home/xml-data/build-dir/AGH-AGHBETA-JOB1/home/service.go:162 +0x5c2
github.com/AdguardTeam/AdGuardHome/home.Main(0xbba4b0, 0x11, 0xbb3c4c, 0x4, 0xbb3674, 0x0)
        /builder/1/bamboo-agent-home/xml-data/build-dir/AGH-AGHBETA-JOB1/home/home.go:112 +0x20c
main.main()
        main.go:20 +0x61
```

* **Version of AdGuard Home server:**
  * v0.101.0-60-gfe05 (Windows)
* **Operating system and version:**
  * Windows 10 x64

**Comment by ddonindia** [comment]
I also got it on ubuntu. I thought something broken on my setup and ignored it  :D

**Comment by ameshkov** [comment]
Fixed by https://github.com/AdguardTeam/AdGuardHome/commit/ea38612a1dee5c6bd397ec6a475516fd222bef67
