### ISSUE TITLE
Crash on reloading the DNS configuration

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#2242]
Obviously, there's a race condition in https://github.com/AdguardTeam/dnsproxy code

```
2020/10/29 06:04:29 [info] Start reconfiguring the server
2020/10/29 06:04:29 [info] Stopping the DNS proxy server
panic: send on closed channel

goroutine 30 [running]:
github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).guardMaxGoroutines(...)
 /root/go/pkg/mod/github.com/!adguard!team/dnsproxy@v0.32.6/proxy/server.go:66
github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).tcpPacketLoop(0xc000141180, 0x11c45a0, 0xc000248140, 0xd86090, 0x3)
 /root/go/pkg/mod/github.com/!adguard!team/dnsproxy@v0.32.6/proxy/server_tcp.go:56 +0x189
created by github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).startListeners
 /root/go/pkg/mod/github.com/!adguard!team/dnsproxy@v0.32.6/proxy/server.go:49 +0x221
```

**Comment by ainar-g** [comment]
<p>Should&#xA0;be fixed as&#xA0;of df34ee5c.</p>
