### ISSUE TITLE
Got 127.0.0.1:50->127.0.0.1:30921: write: broken pipe when update to latest version

### ISSUE THREAD

**Issue by ookangzheng** [AdguardTeam/AdGuardHome#2252]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * v0.104.0
* **How did you setup DNS configuration:**
  * System 
* **Operating system and version:**
  * Debian 10 64bit

### Additional Information
*Error log under `/var/log/AdGuard.err`*

```
2020/11/02 10:05:57 [info] error while responding to a DNS request: conn.Write() returned error, cause: write tcp 127.0.0.1:50->127.0.0.1:30817: write: broken pipe
2020/11/02 10:05:57 [info] error while responding to a DNS request: conn.Write() returned error, cause: write tcp 127.0.0.1:50->127.0.0.1:30819: write: broken pipe
2020/11/02 10:05:58 [info] error while responding to a DNS request: conn.Write() returned error, cause: write tcp 127.0.0.1:50->127.0.0.1:30835: write: broken pipe
2020/11/02 10:05:58 [info] error while responding to a DNS request: conn.Write() returned error, cause: write tcp 127.0.0.1:50->127.0.0.1:30837: write: broken pipe
2020/11/02 10:05:58 [info] error while responding to a DNS request: conn.Write() returned error, cause: write tcp 127.0.0.1:50->127.0.0.1:30841: write: broken pipe
2020/11/02 10:05:58 [info] error while responding to a DNS request: conn.Write() returned error, cause: write tcp 127.0.0.1:50->127.0.0.1:30847: write: broken pipe
2020/11/02 10:05:58 [info] error while responding to a DNS request: conn.Write() returned error, cause: write tcp 127.0.0.1:50->127.0.0.1:30849: write: broken pipe
2020/11/02 10:05:58 [info] error while responding to a DNS request: conn.Write() returned error, cause: write tcp 127.0.0.1:50->127.0.0.1:30851: write: broken pipe
2020/11/02 10:05:58 [info] error while responding to a DNS request: conn.Write() returned error, cause: write tcp 127.0.0.1:50->127.0.0.1:30869: write: broken pipe
2020/11/02 10:05:58 [info] error while responding to a DNS request: conn.Write() returned error, cause: write tcp 127.0.0.1:50->127.0.0.1:30885: write: broken pipe
2020/11/02 10:05:58 [info] error while responding to a DNS request: conn.Write() returned error, cause: write tcp 127.0.0.1:50->127.0.0.1:30889: write: broken pipe
2020/11/02 10:05:58 [info] error while responding to a DNS request: conn.Write() returned error, cause: write tcp 127.0.0.1:50->127.0.0.1:30921: write: broken pipe
2020/11/02 10:05:58 [info] error while responding to a DNS request: conn.Write() returned error, cause: write tcp 127.0.0.1:50->127.0.0.1:30923: write: broken pipe
2020/11/02 10:05:58 [info] error while responding to a DNS request: conn.Write() returned error, cause: write tcp 127.0.0.1:50->127.0.0.1:30937: write: broken pipe
2020/11/02 10:05:58 [info] error while responding to a DNS request: conn.Write() returned error, cause: write tcp 127.0.0.1:50->127.0.0.1:30939: write: broken pipe
2020/11/02 10:05:58 [info] Received signal 'terminated'
2020/11/02 10:05:58 [info] Stopping AdGuard Home
2020/11/02 10:05:58 [info] Stopping HTTP server...
2020/11/02 10:05:58 [info] Stopped HTTP server
2020/11/02 10:05:58 [info] Stopping the DNS proxy server
2020/11/02 10:05:58 [info] Stopped the DNS proxy server
panic: send on closed channel

goroutine 13 [running]:
github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).guardMaxGoroutines(...)
        /root/go/pkg/mod/github.com/!adguard!team/dnsproxy@v0.32.6/proxy/server.go:66
github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).tcpPacketLoop(0xc000148f00, 0x11c5220, 0xc00026c0e0, 0xd8608d, 0x3)
        /root/go/pkg/mod/github.com/!adguard!team/dnsproxy@v0.32.6/proxy/server_tcp.go:56 +0x189
created by github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).startListeners
        /root/go/pkg/mod/github.com/!adguard!team/dnsproxy@v0.32.6/proxy/server.go:45 +0x199
B
```

**Comment by ameshkov** [comment]
It just means that the connection is closed.

Not a bug, but we could change the logging level for these messages to debug just to avoid spamming the log file.

**Comment by ookangzheng** [comment]
Because I recently having timeout issue when a lot of clients connect to AdGuardHome, it said localhost io/timeout 

both query from localhost to localhost 
`service A --> AdguardHome`
