### ISSUE TITLE
[Build Error] semver.simplifyRange is not a function

### ISSUE THREAD

**Issue by setBoolean** [AdguardTeam/AdGuardHome#2784]
I'am getting this error message when trying to build AdGuardHome from source.

Distribution: Arch Linux (stable)
AdGuardHome: 0.105.1
Kernel: 5.11.2
Node: 14.15.4
NPM: 7.6.1

```
1891 verbose stack TypeError: semver.simplifyRange is not a function
1891 verbose stack     at Advisory.[calculateRange] (/usr/lib/node_modules/npm/node_modules/@npmcli/metavuln-calculator/lib/advisory.js:191:16)
1891 verbose stack     at Advisory.load (/usr/lib/node_modules/npm/node_modules/@npmcli/metavuln-calculator/lib/advisory.js:148:28)
1891 verbose stack     at Calculator.[calculate] (/usr/lib/node_modules/npm/node_modules/@npmcli/metavuln-calculator/lib/index.js:59:14)
1891 verbose stack     at async Promise.all (index 0)
1891 verbose stack     at async Map.[init] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/audit-report.js:177:7)
1891 verbose stack     at async Map.run (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/audit-report.js:105:7)
1892 verbose cwd /home/xxx/.cache/yay/adguardhome/src/AdGuardHome-0.105.1
1893 verbose Linux 5.11.2-arch1-1
1894 verbose argv "/usr/bin/node" "/usr/bin/npm" "--prefix" "client" "ci"
1895 verbose node v14.15.4
1896 verbose npm  v7.6.1
1897 error semver.simplifyRange is not a function
1898 verbose exit 1
```

**Comment by setBoolean** [comment]
I will close this issue as it was related to my npm install.

FIX:
1. Delete `$user/.npm` folders.
2. Run `npm clean cache --force`.
3. Build AdGuardHome as usual.
