### ISSUE TITLE
Container keeps restarting in podman running rootless

### ISSUE THREAD

**Issue by dan-m8t** [AdguardTeam/AdGuardHome#3267]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ x] I am running the latest version
- [ x] I checked the documentation and found no answer
- [ x] I checked to make sure that this issue has not already been filed

### Issue Details

As I am not sure if this is a Adguard Home issue or related to podman I decided to file an issue here too.

Here's the issue at the podman project: https://github.com/containers/podman/issues/10673

* **Version of AdGuard Home server:**
  * v0.106.3
* **How did you install AdGuard Home:**
  * podman
* **How did you setup DNS configuration:**
  * router
* **If it's a router or IoT, please write device model:**
  * opnsense
* **CPU architecture:**
  * amd64
* **Operating system and version:**
  * RHEL 8.4

### Expected Behavior
a running container

### Actual Behavior
The container keeps restarting and randomly stops starting at all. Podman throws an error but I am not sure if this is adguard or podman related.

Container logs:

```
2021/06/14 10:24:08.541261 [info] Received signal "terminated"
2021/06/14 10:24:08.541442 [info] Stopping AdGuard Home
2021/06/14 10:24:08.541447 [info] stopping http server...
2021/06/14 10:24:09.041611 [info] stopped http server
2021/06/14 10:24:09.041662 [info] Stopping the DNS proxy server
2021/06/14 10:24:09.041716 [info] udpListen.ReadFrom() returned because we're reading from a closed connection, exiting loop
```

I am not sure if this is related but I set the debug log option and this is what I got:

```
2021/06/14 11:12:55.291760 1#50 [info] Received signal "terminated"
2021/06/14 11:12:55.291790 1#50 [info] Stopping AdGuard Home
2021/06/14 11:12:55.291805 1#50 [info] stopping http server...
2021/06/14 11:12:55.791981 1#50 [info] stopped http server
2021/06/14 11:12:55.792079 1#50 [info] Stopping the DNS proxy server
2021/06/14 11:12:55.792144 1#65 [debug] github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).tcpPacketLoop(): TCP connection has been closed, exiting loop
2021/06/14 11:12:55.792176 1#16 [info] udpListen.ReadFrom() returned because we're reading from a closed connection, exiting loop
2021/06/14 11:12:55.792211 1#50 [info] Stopped the DNS proxy server
2021/06/14 11:12:55.792349 1#50 [debug] github.com/AdguardTeam/AdGuardHome/internal/stats.(*statsCtx).beginTxn(): db.Begin...
2021/06/14 11:12:55.792383 1#50 [debug] github.com/AdguardTeam/AdGuardHome/internal/stats.(*statsCtx).beginTxn(): db.Begin
2021/06/14 11:12:55.792413 1#50 [debug] github.com/AdguardTeam/AdGuardHome/internal/stats.(*statsCtx).flushUnitToDB(): Flushing unit 451019
2021/06/14 11:12:55.815364 1#50 [debug] github.com/AdguardTeam/AdGuardHome/internal/stats.(*statsCtx).commitTxn(): tx.Commit
2021/06/14 11:12:55.815391 1#50 [debug] github.com/AdguardTeam/AdGuardHome/internal/stats.(*statsCtx).Close(): db.Close...
2021/06/14 11:12:55.815430 1#50 [debug] github.com/AdguardTeam/AdGuardHome/internal/stats.(*statsCtx).Close(): db.Close
2021/06/14 11:12:55.815454 1#50 [debug] stats: closed
2021/06/14 11:12:55.816077 1#50 [debug] 117 elements serialized via json in 593.202µs: 43 kB, 383.4102564102564/entry, 5.07µs/entry
2021/06/14 11:12:55.816221 1#50 [debug] querylog: ok "/opt/adguardhome/work/data/querylog.json": 44859 bytes written
2021/06/14 11:12:55.816250 1#50 [debug] Closed all DNS modules
[signal SIGBUS: bus error code=0x2 addr=0x17137dc pc=0x45d479]

runtime stack:
runtime.traceback(...)
        runtime/traceback.go:690
runtime.Stack.func1()
        runtime/mprof.go:821 +0xe5

goroutine 50 [running]:
runtime.systemstack_switch()
        runtime/asm_amd64.s:330 fp=0xc0096f1c10 sp=0xc0096f1c08 pc=0x46e4e0
runtime.Stack(0xc0096f8040, 0x40, 0x40, 0xc0096f8000, 0x150c209c3b)
        runtime/mprof.go:813 +0xee fp=0xc0096f1c80 sp=0xc0096f1c10 pc=0x4301ce
github.com/AdguardTeam/golibs/log.goroutineID(0x27)
        github.com/AdguardTeam/golibs@v0.5.0/log/log.go:156 +0x6f fp=0xc0096f1cf8 sp=0xc0096f1c80 pc=0x774e6f
github.com/AdguardTeam/golibs/log.writeLog(0xd54a44, 0x5, 0x0, 0x0, 0xd61f1e, 0x12, 0x0, 0x0, 0x0)
        github.com/AdguardTeam/golibs@v0.5.0/log/log.go:169 +0x568 fp=0xc0096f1e00 sp=0xc0096f1cf8 pc=0x775528
github.com/AdguardTeam/golibs/log.Debug(...)
        github.com/AdguardTeam/golibs@v0.5.0/log/log.go:138
github.com/AdguardTeam/AdGuardHome/internal/dhcpd.(*raCtx).Close(0xc000347218, 0x16, 0x0)
        github.com/AdguardTeam/AdGuardHome/internal/dhcpd/routeradv.go:275 +0x105 fp=0xc0096f1e58 sp=0xc0096f1e00 pc=0x896365
github.com/AdguardTeam/AdGuardHome/internal/dhcpd.(*v6Server).Stop(0xc000347080)
        github.com/AdguardTeam/AdGuardHome/internal/dhcpd/v6.go:651 +0x38 fp=0xc0096f1ed0 sp=0xc0096f1e58 pc=0x8a4e78
fatal error: unexpected signal during runtime execution
panic during panic
[signal SIGBUS: bus error code=0x2 addr=0x17137dc pc=0x45d479]

runtime stack:
runtime.traceback(...)
        runtime/traceback.go:690
runtime.Stack.func1()
        runtime/mprof.go:821 +0xe5
```

Hope it helps

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by ameshkov** [comment]
panic is definitely unnecessary and can be addressed, CC @ainar-g 

However, this is not the reason AGH stopped. According to the log, it received a signal to stop first, something must've sent it.

**Comment by dan-m8t** [comment]
This is somehow a podman bug, not AGH related so I will close the issue.
