### ISSUE TITLE
panic: page 316 already freed leads to exited with code 2

### ISSUE THREAD

**Issue by ovizii** [AdguardTeam/AdGuardHome#3517]
I had an issue recently, which was fixed with the latest edge build, v0.107.0-a.144+9f52adf3 - but now I seem to have a (possible) follow-up error which might be related. => link to last issue: https://github.com/AdguardTeam/AdGuardHome/issues/3506

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details

After the latest  :edge update I get this error:

```
docker-compose  logs -f
Attaching to adguardhome
adguardhome    | 2021/08/30 07:05:08.349316 [info] AdGuard Home, version v0.107.0-a.149+e064e0f2
adguardhome    | 2021/08/30 07:05:08.394758 [info] Initializing auth module: /opt/adguardhome/work/data/sessions.db
adguardhome    | 2021/08/30 07:05:08.394922 [info] auth: initialized.  users:1  sessions:1
adguardhome    | 2021/08/30 07:05:08.394944 [info] Initialize web module
adguardhome    | panic: page 316 already freed
adguardhome    |
adguardhome    | goroutine 1 [running]:
adguardhome    | go.etcd.io/bbolt.(*freelist).free(0xc0003fe700, 0x2b02, 0x7f11fe6aa000)
adguardhome    |        go.etcd.io/bbolt@v1.3.5/freelist.go:175 +0x3e7
adguardhome    | go.etcd.io/bbolt.(*Bucket).free.func1(0x7f11fe6aa000, 0x0, 0x0)
adguardhome    |        go.etcd.io/bbolt@v1.3.5/bucket.go:684 +0x51
adguardhome    | go.etcd.io/bbolt.(*Bucket)._forEachPageNode(0xc000484140, 0x13c, 0x0, 0xc000262a00)
adguardhome    |        go.etcd.io/bbolt@v1.3.5/bucket.go:506 +0x84
adguardhome    | go.etcd.io/bbolt.(*Bucket).forEachPageNode(0xc000484140, 0xc000262a00)
adguardhome    |        go.etcd.io/bbolt@v1.3.5/bucket.go:499 +0x73
adguardhome    | go.etcd.io/bbolt.(*Bucket).free(0xc000484140)
adguardhome    |        go.etcd.io/bbolt@v1.3.5/bucket.go:682 +0x67
adguardhome    | go.etcd.io/bbolt.(*Bucket).DeleteBucket(0xc0004702b8, 0x7f11fee273b8, 0x8, 0x8, 0x7f11fee273c0, 0x10)
adguardhome    |        go.etcd.io/bbolt@v1.3.5/bucket.go:250 +0x286
adguardhome    | go.etcd.io/bbolt.(*Tx).DeleteBucket(...)
adguardhome    |        go.etcd.io/bbolt@v1.3.5/tx.go:121
adguardhome    | github.com/AdguardTeam/AdGuardHome/internal/stats.newBucketWalker.func1(0x7f11fee273b8, 0x8, 0x8, 0xc000484140, 0xc000484140, 0x0)
adguardhome    |        github.com/AdguardTeam/AdGuardHome/internal/stats/unit.go:137 +0x97
adguardhome    | go.etcd.io/bbolt.(*Tx).ForEach.func1(0x7f11fee273b8, 0x8, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0)
adguardhome    |        go.etcd.io/bbolt@v1.3.5/tx.go:129 +0x8c
adguardhome    | go.etcd.io/bbolt.(*Bucket).ForEach(0xc0004702b8, 0xc000262c68, 0xc0001b72c0, 0xc000262c80)
adguardhome    |        go.etcd.io/bbolt@v1.3.5/bucket.go:390 +0x103
adguardhome    | go.etcd.io/bbolt.(*Tx).ForEach(0xc0004702a0, 0xc0001b72c0, 0x6e08e, 0xc0001b72c0)
adguardhome    |        go.etcd.io/bbolt@v1.3.5/tx.go:128 +0x67
adguardhome    | github.com/AdguardTeam/AdGuardHome/internal/stats.createObject(0xc000194a80, 0x23, 0x5a, 0x0, 0x0, 0x1faf118, 0x1faf0f8, 0x0, 0x0, 0x0, ...)
adguardhome    |        github.com/AdguardTeam/AdGuardHome/internal/stats/unit.go:93 +0x3c7
adguardhome    | github.com/AdguardTeam/AdGuardHome/internal/stats.New(...)
adguardhome    |        github.com/AdguardTeam/AdGuardHome/internal/stats/stats.go:35
adguardhome    | github.com/AdguardTeam/AdGuardHome/internal/home.initDNSServer(0xc0003e7320, 0x0)
adguardhome    |        github.com/AdguardTeam/AdGuardHome/internal/home/dns.go:41 +0x1d3
adguardhome    | github.com/AdguardTeam/AdGuardHome/internal/home.run(0x0, 0x7ffe5a855f2e, 0x26, 0x7ffe5a855f63, 0x15, 0xc000137d30, 0x10, 0x10, 0x0, 0x0, ...)
adguardhome    |        github.com/AdguardTeam/AdGuardHome/internal/home/home.go:423 +0xdfe
adguardhome    | github.com/AdguardTeam/AdGuardHome/internal/home.Main(0x206e980, 0x208ffa0)
adguardhome    |        github.com/AdguardTeam/AdGuardHome/internal/home/home.go:125 +0x239
adguardhome    | main.main()
adguardhome    |        github.com/AdguardTeam/AdGuardHome/main.go:13 +0x39
adguardhome exited with code 2

```

* **Version of AdGuard Home server:**
  * v0.107.0-a.149+e064e0f2
* **How did you install AdGuard Home:**
  * Docker
* **How did you setup DNS configuration:**
  * manually entered the adguardhome as DNS for specific devices at home
* **CPU architecture:**
  * AMD64
* **Operating system and version:**
  * Debian 10 (latest)

### Expected Behavior
docker-compose up -d starts the adguard home container and makes it usable

### Actual Behavior
the container stops with the error message above

**Comment by ainar-g** [comment]
Thank you for the report!  Looks like an issue in the `go.etcd.io/bbolt` module.  We'll investigate.

**Comment by ainar-g** [comment]
The version v0.107.0-a.150+1265be50 on the `edge` channel contains an update of that module.  If that still won't fix the issue then I think it's better that you just remove the corrupted statistics file.

**Comment by ovizii** [comment]
> The version v0.107.0-a.150+1265be50 on the `edge` channel contains an update of that module. If that still won't fix the issue then I think it's better that you just remove the corrupted statistics file.

Thanks for looking into it, the problem isn't fixed with v0.107.0-a.150+1265be50. 

Any hints on how to remove "the corrupted statistics file"? Which file do I need to remove? I don't really care about stats. 
The only file mentioned in the error is /opt/adguardhome/work/data/sessions.db but that doesn't sound like a stats file.

**Comment by ainar-g** [comment]
It's the file `data/stats.db` inside your workdir.

**Comment by ovizii** [comment]
thanks that worked!
