### ISSUE TITLE
panic during installation configuration

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdGuardHome#3596]
1.  Start AdGuardHome v0.107.0-b.10.
2.  Configure as always up to step 3.
3.  Press Next.

   ###  Expected

The next page is shown, no errors.

   ###  Actual

NetworkError, panic in the log:

```none
2021/09/14 17:38:32.411528 4441#6 [debug] web: plain: http: panic serving 127.0.0.1:52648: runtime error: invalid memory address or nil pointer dereference
goroutine 6 [running]:
net/http.(*conn).serve.func1(0xc0004a4000)
        net/http/server.go:1804 +0x153
panic(0xc5d3c0, 0x24d7c90)
        runtime/panic.go:971 +0x499
github.com/AdguardTeam/AdGuardHome/internal/home.copyInstallSettings(...)
        github.com/AdguardTeam/AdGuardHome/internal/home/controlinstall.go:262
github.com/AdguardTeam/AdGuardHome/internal/home.(*Web).handleInstallConfigure(0xc0002980e0, 0x20865a0, 0xc000130620, 0xc000132500)
        github.com/AdguardTeam/AdGuardHome/internal/home/controlinstall.go:311 +0x2b1
github.com/AdguardTeam/AdGuardHome/internal/home.ensure.func1(0x20865a0, 0xc000130620, 0xc000132500)
        github.com/AdguardTeam/AdGuardHome/internal/home/control.go:235 +0x214
```

**Comment by ainar-g** [comment]
We'll wait to see if there are any other embarrassing bugs like this and release v0.107.0-b.11.
