### ISSUE TITLE
Panic on CTRL-C (v0.107.0-b.11)

### ISSUE THREAD

**Issue by timkgh** [AdguardTeam/AdGuardHome#3655]
### Issue Details

Panic when exiting process (CTRL-C)

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x2c8 pc=0x66f118]

goroutine 655 [running]:
github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).Resolve(0x0, 0xc0005c7b00, 0x0, 0x0)
	github.com/AdguardTeam/dnsproxy@v0.39.5/proxy/proxy.go:480 +0x30
github.com/AdguardTeam/AdGuardHome/internal/dnsforward.(*Server).processUpstream(0xc000276f00, 0xc00012bd60, 0x0)
	github.com/AdguardTeam/AdGuardHome/internal/dnsforward/dns.go:544 +0x8c
github.com/AdguardTeam/AdGuardHome/internal/dnsforward.(*Server).handleDNSRequest(0xc000276f00, 0xc000188380, 0xc0005c7b00, 0x0, 0x0)
	github.com/AdguardTeam/AdGuardHome/internal/dnsforward/dns.go:102 +0x2dc
github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).handleDNSRequest(0xc000188380, 0xc0005c7b00, 0x2123b60, 0x28)
	github.com/AdguardTeam/dnsproxy@v0.39.5/proxy/server.go:127 +0x240
github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).udpHandlePacket(0xc000188380, 0xc000bb12f0, 0x28, 0x28, 0xc00047751c, 0x4, 0x4, 0xc0004944e0, 0xc000306040)
	github.com/AdguardTeam/dnsproxy@v0.39.5/proxy/server_udp.go:105 +0x2fc
github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).udpPacketLoop.func1(0xc000188380, 0xc000bb12f0, 0x28, 0x28, 0xc00047751c, 0x4, 0x4, 0xc0004944e0, 0xc000306040, 0x1cc76e8, ...)
	github.com/AdguardTeam/dnsproxy@v0.39.5/proxy/server_udp.go:74 +0x7c
created by github.com/AdguardTeam/dnsproxy/proxy.(*Proxy).udpPacketLoop
	github.com/AdguardTeam/dnsproxy@v0.39.5/proxy/server_udp.go:73 +0x500
```

* **Version of AdGuard Home server:**
  * v0.107.0-b.11
* **How did you install AdGuard Home:**
  * Manual, just running the process by hand for now
* **How did you setup DNS configuration:**
  * router
* **If it's a router or IoT, please write device model:**
  * EdgeRouter ER-12
* **CPU architecture:**
  * mips64_softfloat
* **Operating system and version:**
  * EdgeOS v2.0.9-hotfix.2

### Expected Behavior
Exit cleanly, no crash. v0.106.3 is well behaved wrt CTRL-C

### Actual Behavior
panic

**Comment by EugeneOne1** [comment]
@timkgh, Hello and thank you for the report.  Latest edge build contains our solution for the issue.  Could you please check if the problem remains?
