### ISSUE TITLE
AdGuardHome stops responding on DNS requests and can only be killed with SIGKILL

### ISSUE THREAD

**Issue by zhulik** [AdguardTeam/AdGuardHome#3936]
Have a question or an idea? Please search it [on our forum](https://github.com/AdguardTeam/AdGuardHome/discussions) to make sure it was not yet asked. If you cannot find what you had in mind, please [submit it here](https://github.com/AdguardTeam/AdGuardHome/discussions/new).

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details

* **Version of AdGuard Home server:**
  * 0.106.3
* **How did you install AdGuard Home:**
  * [Arch Linux User Repository](https://aur.archlinux.org/packages/adguardhome/) 
  * [build script](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=adguardhome)
* **How did you setup DNS configuration:**
  * Router
* **If it's a router or IoT, please write device model:**
  * Fritz!Box 6591 Cable
* **CPU architecture:**
  * AMD64
* **Operating system and version:**
  * Arch Linux
 
### Expected Behavior
No freezes, it just works

### Actual Behavior
AdGuardHome stops responding and freezes. It does not react on SIGTERM, so I have to use SIGKILL to restart it. 
Sometimes it happens few times a day, sometimes it works without issues for days.

### Screenshots

<details><summary>Screenshot:</summary>

</details>

### Additional Information

I will provide logs if you give me a hint on how to enable them. In my journactl output I see only

```
Started AdGuard Home: Network-level blocker.
```
and
```
Stopped AdGuard Home: Network-level blocker.
```
I'm not sure if the web interface works because my local network relies on hanging AdGuardHome DNS

**Comment by ppfeufer** [comment]
Check if you have browsing security or parental control activated. If so, it's probably related to this » https://github.com/AdguardTeam/AdGuardHome/discussions/2742

**Comment by ainar-g** [comment]
Hello.  We've fixed a few similar issues during the v0.107.0 cycle.  Can you install one of the betas and see if that fixes the issue for you?

**Comment by ppfeufer** [comment]
`v0.107.0-b.15` installed, let's see

**Comment by zhulik** [comment]
Hmm, apparently I can't build the latest beta with node 17:
```
ERROR in ./src/lib/theme/Text.module.pcss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /home/user/adguardhome/src/AdGuardHome-0.107.0-b.15/client2/node_modules/postcss/package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:429:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:683:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (/home/user/adguardhome/src/AdGuardHome-0.107.0-b.15/client2/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/user/adguardhome/src/AdGuardHome-0.107.0-b.15/client2/node_modules/css-loader/dist/index.js:12:39)
    at processResult (/home/user/adguardhome/src/AdGuardHome-0.107.0-b.15/client2/node_modules/webpack/lib/NormalModule.js:597:19)
    at /home/user/adguardhome/src/AdGuardHome-0.107.0-b.15/client2/node_modules/webpack/lib/NormalModule.js:691:5
    at /home/user/adguardhome/src/AdGuardHome-0.107.0-b.15/client2/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /home/user/adguardhome/src/AdGuardHome-0.107.0-b.15/client2/node_modules/loader-runner/lib/LoaderRunner.js:185:11
    at loadLoader (/home/user/adguardhome/src/AdGuardHome-0.107.0-b.15/client2/node_modules/loader-runner/lib/loadLoader.js:33:11)
    at iteratePitchingLoaders (/home/user/adguardhome/src/AdGuardHome-0.107.0-b.15/client2/node_modules/loader-runner/lib/LoaderRunner.js:182:2)
    at runLoaders (/home/user/adguardhome/src/AdGuardHome-0.107.0-b.15/client2/node_modules/loader-runner/lib/LoaderRunner.js:397:2)
    at NormalModule.doBuild (/home/user/adguardhome/src/AdGuardHome-0.107.0-b.15/client2/node_modules/webpack/lib/NormalModule.js:645:3)
    at NormalModule.build (/home/user/adguardhome/src/AdGuardHome-0.107.0-b.15/client2/node_modules/webpack/lib/NormalModule.js:790:15)
    at /home/user/adguardhome/src/AdGuardHome-0.107.0-b.15/client2/node_modules/webpack/lib/Compilation.js:1238:12
```
Could be related to https://github.com/postcss/postcss/issues/1562

**Comment by ainar-g** [comment]
@zhulik, the prebuilt beta releases are available on the [releases page][1].

[1]: https://github.com/AdguardTeam/AdGuardHome/releases

**Comment by ppfeufer** [comment]
So far secure browsing working with `v0.107.0-b.15` without AGH hanging itself. (Just the DHCP settings page is gone/empty)

**Comment by zhulik** [comment]
I disabled secure browsing, parental control was never enabled and everything seems to work fine. I'll test it again with 0.107 once it's released
