### ISSUE TITLE
*Crash* when trying to start (with corrupted stats.db)

### ISSUE THREAD

**Issue by Caesarovich** [AdguardTeam/AdGuardHome#4142]
### Issue Details

**Note:** I am not sure if the error should be given here or on https://github.com/etcd-io/bbolt , I am not a Go person and I don't quite get what is at fault here.

I have gotten the following issue while trying to restart my AdGuardHome.
My guess is that some data/string got corrupted/unproperly formatted in **stats.db** and `panic: runtime error: slice bounds out of range [::-2]` is an error due to trying string operations on a corrupted/unproperly formatted string.

I resolved the issue by deleting **stats.db**

## Version details
AdGuard Home
Version: v0.107.2
Channel: release
Go version: go1.16.12
Build time: 2021-12-29T19:56:24Z+0000
GOOS: linux
GOARCH: arm
GOARM: v7
Race: false

## Error stack trace:

```
2022/01/15 17:52:42.824897 [info] AdGuard Home, version v0.107.2
2022/01/15 17:52:42.865158 [info] Initializing auth module: /opt/AdGuardHome/data/sessions.db
2022/01/15 17:52:42.866117 [info] auth: initialized.  users:1  sessions:2
2022/01/15 17:52:42.866520 [info] Initialize web module
panic: runtime error: slice bounds out of range [::-2]

goroutine 1 [running]:
go.etcd.io/bbolt.unsafeByteSlice(...)
        go.etcd.io/bbolt@v1.3.6/unsafe.go:27
go.etcd.io/bbolt.(*leafPageElement).key(...)
        go.etcd.io/bbolt@v1.3.6/page.go:126
go.etcd.io/bbolt.(*Cursor).keyValue(0x41f93f8, 0x2357378, 0x0, 0x0, 0x1, 0x40956d0, 0x0, 0x1)
        go.etcd.io/bbolt@v1.3.6/cursor.go:350 +0x1c0
go.etcd.io/bbolt.(*Cursor).First(0x41f93f8, 0x0, 0x0, 0x2357378, 0x4095601, 0x2e0700, 0x65000)
        go.etcd.io/bbolt@v1.3.6/cursor.go:44 +0xf8
go.etcd.io/bbolt.(*Bucket).ForEach(0x4154920, 0x41f9464, 0x8, 0x8)
        go.etcd.io/bbolt@v1.3.6/bucket.go:389 +0x8c
go.etcd.io/bbolt.(*Bucket).DeleteBucket(0x40c650c, 0x66be7100, 0x8, 0x8, 0x10, 0x10)
        go.etcd.io/bbolt@v1.3.6/bucket.go:232 +0x16c
go.etcd.io/bbolt.(*Tx).DeleteBucket(...)
        go.etcd.io/bbolt@v1.3.6/tx.go:121
github.com/AdguardTeam/AdGuardHome/internal/stats.newBucketWalker.func1(0x66be7100, 0x8, 0x8, 0x4154920, 0x4154920, 0x66bfb000)
        github.com/AdguardTeam/AdGuardHome/internal/stats/unit.go:141 +0x70
go.etcd.io/bbolt.(*Tx).ForEach.func1(0x66be7100, 0x8, 0x8, 0x0, 0x0, 0x0, 0x0, 0x403e6c0)
        go.etcd.io/bbolt@v1.3.6/tx.go:129 +0x70
go.etcd.io/bbolt.(*Bucket).ForEach(0x40c650c, 0x41f9520, 0x4095690, 0x5f0dfc)
        go.etcd.io/bbolt@v1.3.6/bucket.go:390 +0xf8
go.etcd.io/bbolt.(*Tx).ForEach(0x40c6500, 0x4095690, 0x6f5df, 0x4095690)
        go.etcd.io/bbolt@v1.3.6/tx.go:128 +0x58
github.com/AdguardTeam/AdGuardHome/internal/stats.createObject(0x4098be0, 0x1e, 0x1, 0x0, 0x1b45734, 0x1b45724, 0x0, 0x0, 0x0, 0x0)
        github.com/AdguardTeam/AdGuardHome/internal/stats/unit.go:97 +0x314
github.com/AdguardTeam/AdGuardHome/internal/stats.New(...)
        github.com/AdguardTeam/AdGuardHome/internal/stats/stats.go:34
github.com/AdguardTeam/AdGuardHome/internal/home.initDNSServer(0x40b2ed0, 0x0)
        github.com/AdguardTeam/AdGuardHome/internal/home/dns.go:55 +0x130
github.com/AdguardTeam/AdGuardHome/internal/home.run(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        github.com/AdguardTeam/AdGuardHome/internal/home/home.go:476 +0xa9c
github.com/AdguardTeam/AdGuardHome/internal/home.Main(0x1c05594, 0x1c146b0)
        github.com/AdguardTeam/AdGuardHome/internal/home/home.go:131 +0x11c
main.main()
        github.com/AdguardTeam/AdGuardHome/main.go:17 +0x28
```

**Comment by EugeneOne1** [comment]
@Caesarovich, hello.  It seems, the [bbolt](https://github.com/etcd-io/bbolt) library inaccurately deals with some indexes in corrupted files, the related issue etcd-io/bbolt#182 still opened.

We've improved an error message for these cases in the latest `edge` build.  However, anyone who faced this issue generally should get rid of  `stats.db` file.

I'll close the issue for now but feel free to open those on every unrecovered panic you'll face.  Thanks.
