### ISSUE TITLE
problem with building by source

### ISSUE THREAD

**Issue by ibksturm** [AdguardTeam/AdGuardHome#471]
hi guys

on try up building by sources, it'l becomes this error log

```
43635 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
43636 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
43637 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
43637 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
43637 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
43637 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
43638 verbose stack Error: uglifyjs-webpack-plugin@0.4.6 postinstall: `node lib/post_install.js`
43638 verbose stack Exit status 1
43638 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
43638 verbose stack     at EventEmitter.emit (events.js:182:13)
43638 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
43638 verbose stack     at ChildProcess.emit (events.js:182:13)
43638 verbose stack     at maybeClose (internal/child_process.js:978:16)
43638 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
43639 verbose pkgid uglifyjs-webpack-plugin@0.4.6
43640 verbose cwd /root/AdGuardHome
43641 verbose Linux 4.18.0-11-generic
43642 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "--prefix" "client" "install"
43643 verbose node v11.2.0
43644 verbose npm  v6.4.1
43645 error code ELIFECYCLE
43646 error errno 1
43647 error uglifyjs-webpack-plugin@0.4.6 postinstall: `node lib/post_install.js`
43647 error Exit status 1
43648 error Failed at the uglifyjs-webpack-plugin@0.4.6 postinstall script.
43648 error This is probably not a problem with npm. There is likely additional logging output above.
43649 verbose exit [ 1, true ]
```

any fancy idear, what i could do?

golang and node are fresh new installed

**Comment by hmage** [comment]
Hi!

My first thought is that probably `client/node_modules` got interrupted and on second run it fails -- happened to me before. 

Until I can get ahold of a dev who does js, try this: `make clean && make`, it'll nuke `client/node_modules` and npm will try from fresh.

If that doesn't work, let me know.

**Comment by ibksturm** [comment]
let you know ;) 

but don't worry i'm using at them moment the common building, my other problem looks like solved
