### ISSUE TITLE
Crash on invalid DNS request

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardHome#491]
```2018/12/20 10:18:52 Got invalid number of questions: 0
panic: runtime error: index out of range

goroutine 160766 [running]:
github.com/AdguardTeam/AdGuardHome/dnsforward.(*dayTop).addEntry(0xd5b640, 0xc002c63600, 0xc001b6c2d0, 0xbefeee7723bce898, 0x4326d7f0438ac, 0xd5ba20, 0x0, 0x0)
        /opt/AdguardDNS/dnsforward/querylog_top.go:160 +0x602
github.com/AdguardTeam/AdGuardHome/dnsforward.logRequest(0xc001b6c2d0, 0xc0033e3440, 0xc002efed60, 0x2b35e, 0xc002388ee0, 0xe, 0x0, 0x0)
        /opt/AdguardDNS/dnsforward/querylog.go:96 +0x429
github.com/AdguardTeam/AdGuardHome/dnsforward.(*Server).handlePacket(0xd5bd00, 0xc001688000, 0xc, 0xc, 0xa1f420, 0xc0039310e0, 0xc00009c050)
        /opt/AdguardDNS/dnsforward/dnsforward.go:509 +0x383
created by github.com/AdguardTeam/AdGuardHome/dnsforward.(*Server).packetLoop
        /opt/AdguardDNS/dnsforward/dnsforward.go:151 +0x2a5```

**Comment by ameshkov** [comment]
Resolved in the master branch
