### ISSUE TITLE
Add minimum supported node version to README.md

### ISSUE THREAD

**Issue by nezorflame** [AdguardTeam/AdGuardHome#564]
### Steps to reproduce

1. `git clone https://github.com/AdguardTeam/AdGuardHome.git && cd AdGuardHome`
2. `make`

### Expected behavior

Build is expected to work fine, with no errors.

### Actual behavior

Build fails with errors on step `NODE_ENV=production ./node_modules/.bin/webpack --config webpack.prod.js`.

**npm version output**
```
{ npm: '3.10.10',
  ares: '1.10.1-DEV',
  http_parser: '2.7.1',
  icu: '50.1.2',
  modules: '48',
  napi: '3',
  node: '6.14.3',
  openssl: '1.0.2k-fips',
  uv: '1.23.2',
  v8: '5.1.281.111',
  zlib: '1.2.7' }
```

**npm-debug.log**

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   '--prefix',
1 verbose cli   'client',
1 verbose cli   'run',
1 verbose cli   'build-prod' ]
2 info using npm@3.10.10
3 info using node@v6.14.3
4 verbose run-script [ 'prebuild-prod', 'build-prod', 'postbuild-prod' ]
5 info lifecycle dashboard@0.1.0~prebuild-prod: dashboard@0.1.0
6 silly lifecycle dashboard@0.1.0~prebuild-prod: no script for prebuild-prod, continuing
7 info lifecycle dashboard@0.1.0~build-prod: dashboard@0.1.0
8 verbose lifecycle dashboard@0.1.0~build-prod: unsafe-perm in lifecycle true
9 verbose lifecycle dashboard@0.1.0~build-prod: PATH: <my $PATH here>
10 verbose lifecycle dashboard@0.1.0~build-prod: CWD: <my $GOPATH here>/src/github.com/AdguardTeam/AdGuardHome/client
11 silly lifecycle dashboard@0.1.0~build-prod: Args: [ '-c',
11 silly lifecycle   'NODE_ENV=production ./node_modules/.bin/webpack --config webpack.prod.js' ]
12 silly lifecycle dashboard@0.1.0~build-prod: Returned: code: 2  signal: null
13 info lifecycle dashboard@0.1.0~build-prod: Failed to exec build-prod script
14 verbose stack Error: dashboard@0.1.0 build-prod: `NODE_ENV=production ./node_modules/.bin/webpack --config webpack.prod.js`
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:920:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
15 verbose pkgid dashboard@0.1.0
16 verbose cwd <my $GOPATH here>/src/github.com/AdguardTeam/AdGuardHome
17 error Linux 3.10.0-957.1.3.el7.x86_64
18 error argv "/usr/bin/node" "/usr/bin/npm" "--prefix" "client" "run" "build-prod"
19 error node v6.14.3
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error dashboard@0.1.0 build-prod: `NODE_ENV=production ./node_modules/.bin/webpack --config webpack.prod.js`
22 error Exit status 2
23 error Failed at the dashboard@0.1.0 build-prod script 'NODE_ENV=production ./node_modules/.bin/webpack --config webpack.prod.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the dashboard package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     NODE_ENV=production ./node_modules/.bin/webpack --config webpack.prod.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs dashboard
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls dashboard
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Go version:| `v1.11.5`
| Version of AdGuard Home server:| `v0.92-hotfix2`, `master`
| How did you setup DNS configuration:| `System`
| If it's a router or IoT, please write device model:| `Neither`
| Operating system and version:| `CentOS 7`

**Comment by ameshkov** [comment]
> 2 info using npm@3.10.10
> 3 info using node@v6.14.3

Newer npm/node versions are required to build it.

**Comment by nezorflame** [comment]
@ameshkov thanks for your reply! Would be nice to post minimal requirements in the README then, since my installation is actually the latest possible in the official repos.

**Comment by ameshkov** [comment]
Yeah, it makes sense:)

**Comment by ameshkov** [comment]
@IldarKamalov let's specify LTS as the minimum supported version, we don't test it with older versions anyway

**Comment by nezorflame** [comment]
Just a heads-up - it worked with node v11 👍
