### ISSUE TITLE
The NodeJS frontend fails to build

### ISSUE THREAD

**Issue by yurivict** [AdguardTeam/AdGuardHome#6585]
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not [ask a question or ask for help](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a)

- [X] I have set up AdGuard Home correctly and [configured clients to use it](https://github.com/AdguardTeam/AdGuardHome/wiki/Clients). (Use the [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions/categories/q-a) for help with installing and configuring clients.)

### Platform (OS and CPU architecture)

FreeBSD, AMD64 (aka x86_64)

### Installation

GitHub releases or script from README

### Setup

On one machine

### AdGuard Home version

BABE

### Action

My attempt to update the FreeBSD to 0.107.43 failed because the command building the front-end failed:
```gmake js-deps js-build```.

### Expected result

n/a

### Actual result

```
===>  Building for adguardhome-0.107.43
npm --prefix client --quiet --no-progress --ignore-engines --ignore-optional --ignore-platform --ignore-scripts ci
npm WARN deprecated @babel/plugin-proposal-class-properties@7.8.3: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
npm WARN deprecated @babel/plugin-proposal-nullish-coalescing-operator@7.10.4: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-nullish-coalescing-operator instead.
npm WARN deprecated @babel/plugin-proposal-optional-chaining@7.10.4: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-chaining instead.
npm WARN deprecated @stylelint/postcss-markdown@0.36.2: Use the original unforked package instead: postcss-markdown
npm WARN deprecated @babel/plugin-proposal-dynamic-import@7.8.3: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-dynamic-import instead.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated @babel/plugin-proposal-unicode-property-regex@7.8.8: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-unicode-property-regex instead.
npm WARN deprecated @babel/plugin-proposal-optional-catch-binding@7.8.3: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-catch-binding instead.
npm WARN deprecated @babel/plugin-proposal-async-generator-functions@7.8.3: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-async-generator-functions instead.
npm WARN deprecated @babel/plugin-proposal-numeric-separator@7.8.3: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-numeric-separator instead.
npm WARN deprecated @babel/plugin-proposal-object-rest-spread@7.9.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-object-rest-spread instead.
npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
npm WARN deprecated @babel/plugin-proposal-json-strings@7.8.3: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-json-strings instead.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated mini-create-react-context@0.4.0: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated source-map-url@0.4.0: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated eslint-loader@4.0.2: This loader has been deprecated. Please use eslint-webpack-plugin
npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm WARN deprecated @stylelint/postcss-css-in-js@0.37.3: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated axios@0.19.2: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm WARN deprecated core-js@1.2.7: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.

added 1809 packages, and audited 1810 packages in 2m

135 packages are looking for funding
  run `npm fund` for details

45 vulnerabilities (1 low, 17 moderate, 26 high, 1 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
npm --prefix client run build-prod

> dashboard@0.1.0 build-prod
> cross-env BUILD_ENV=prod webpack --config webpack.prod.js

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:68:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (/usr/ports/www/adguardhome/work/github.com/AdguardTeam/AdGuardHome@v0.107.43/client/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/usr/ports/www/adguardhome/work/github.com/AdguardTeam/AdGuardHome@v0.107.43/client/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/usr/ports/www/adguardhome/work/github.com/AdguardTeam/AdGuardHome@v0.107.43/client/node_modules/webpack/lib/NormalModule.js:471:10)
    at /usr/ports/www/adguardhome/work/github.com/AdguardTeam/AdGuardHome@v0.107.43/client/node_modules/webpack/lib/NormalModule.js:503:5
    at /usr/ports/www/adguardhome/work/github.com/AdguardTeam/AdGuardHome@v0.107.43/client/node_modules/webpack/lib/NormalModule.js:358:12
    at /usr/ports/www/adguardhome/work/github.com/AdguardTeam/AdGuardHome@v0.107.43/client/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/usr/ports/www/adguardhome/work/github.com/AdguardTeam/AdGuardHome@v0.107.43/client/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/usr/ports/www/adguardhome/work/github.com/AdguardTeam/AdGuardHome@v0.107.43/client/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /usr/ports/www/adguardhome/work/github.com/AdguardTeam/AdGuardHome@v0.107.43/client/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/usr/ports/www/adguardhome/work/github.com/AdguardTeam/AdGuardHome@v0.107.43/client/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/usr/ports/www/adguardhome/work/github.com/AdguardTeam/AdGuardHome@v0.107.43/client/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/usr/ports/www/adguardhome/work/github.com/AdguardTeam/AdGuardHome@v0.107.43/client/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/usr/ports/www/adguardhome/work/github.com/AdguardTeam/AdGuardHome@v0.107.43/client/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /usr/ports/www/adguardhome/work/github.com/AdguardTeam/AdGuardHome@v0.107.43/client/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /usr/ports/www/adguardhome/work/github.com/AdguardTeam/AdGuardHome@v0.107.43/client/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read/context:68:3)
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:68:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (/usr/ports/www/adguardhome/work/github.com/AdguardTeam/AdGuardHome@v0.107.43/client/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/usr/ports/www/adguardhome/work/github.com/AdguardTeam/AdGuardHome@v0.107.43/client/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/usr/ports/www/adguardhome/work/github.com/AdguardTeam/AdGuardHome@v0.107.43/client/node_modules/webpack/lib/NormalModule.js:471:10)
    at /usr/ports/www/adguardhome/work/github.com/AdguardTeam/AdGuardHome@v0.107.43/client/node_modules/webpack/lib/NormalModule.js:503:5
    at /usr/ports/www/adguardhome/work/github.com/AdguardTeam/AdGuardHome@v0.107.43/client/node_modules/webpack/lib/NormalModule.js:358:12
    at /usr/ports/www/adguardhome/work/github.com/AdguardTeam/AdGuardHome@v0.107.43/client/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/usr/ports/www/adguardhome/work/github.com/AdguardTeam/AdGuardHome@v0.107.43/client/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/usr/ports/www/adguardhome/work/github.com/AdguardTeam/AdGuardHome@v0.107.43/client/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /usr/ports/www/adguardhome/work/github.com/AdguardTeam/AdGuardHome@v0.107.43/client/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/usr/ports/www/adguardhome/work/github.com/AdguardTeam/AdGuardHome@v0.107.43/client/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/usr/ports/www/adguardhome/work/github.com/AdguardTeam/AdGuardHome@v0.107.43/client/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/usr/ports/www/adguardhome/work/github.com/AdguardTeam/AdGuardHome@v0.107.43/client/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/usr/ports/www/adguardhome/work/github.com/AdguardTeam/AdGuardHome@v0.107.43/client/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /usr/ports/www/adguardhome/work/github.com/AdguardTeam/AdGuardHome@v0.107.43/client/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /usr/ports/www/adguardhome/work/github.com/AdguardTeam/AdGuardHome@v0.107.43/client/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read/context:68:3)
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:68:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (/usr/ports/www/adguardhome/work/github.com/AdguardTeam/AdGuardHome@v0.107.43/client/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/usr/ports/www/adguardhome/work/github.com/AdguardTeam/AdGuardHome@v0.107.43/client/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/usr/ports/www/adguardhome/work/github.com/AdguardTeam/AdGuardHome@v0.107.43/client/node_modules/webpack/lib/NormalModule.js:471:10)
    at /usr/ports/www/adguardhome/work/github.com/AdguardTeam/AdGuardHome@v0.107.43/client/node_modules/webpack/lib/NormalModule.js:503:5
    at /usr/ports/www/adguardhome/work/github.com/AdguardTeam/AdGuardHome@v0.107.43/client/node_modules/webpack/lib/NormalModule.js:358:12
    at /usr/ports/www/adguardhome/work/github.com/AdguardTeam/AdGuardHome@v0.107.43/client/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/usr/ports/www/adguardhome/work/github.com/AdguardTeam/AdGuardHome@v0.107.43/client/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/usr/ports/www/adguardhome/work/github.com/AdguardTeam/AdGuardHome@v0.107.43/client/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /usr/ports/www/adguardhome/work/github.com/AdguardTeam/AdGuardHome@v0.107.43/client/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/usr/ports/www/adguardhome/work/github.com/AdguardTeam/AdGuardHome@v0.107.43/client/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/usr/ports/www/adguardhome/work/github.com/AdguardTeam/AdGuardHome@v0.107.43/client/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/usr/ports/www/adguardhome/work/github.com/AdguardTeam/AdGuardHome@v0.107.43/client/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/usr/ports/www/adguardhome/work/github.com/AdguardTeam/AdGuardHome@v0.107.43/client/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /usr/ports/www/adguardhome/work/github.com/AdguardTeam/AdGuardHome@v0.107.43/client/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /usr/ports/www/adguardhome/work/github.com/AdguardTeam/AdGuardHome@v0.107.43/client/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read/context:68:3)
node:internal/crypto/hash:68
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:68:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (/usr/ports/www/adguardhome/work/github.com/AdguardTeam/AdGuardHome@v0.107.43/client/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/usr/ports/www/adguardhome/work/github.com/AdguardTeam/AdGuardHome@v0.107.43/client/node_modules/webpack/lib/NormalModule.js:417:16)
    at /usr/ports/www/adguardhome/work/github.com/AdguardTeam/AdGuardHome@v0.107.43/client/node_modules/webpack/lib/NormalModule.js:452:10
    at /usr/ports/www/adguardhome/work/github.com/AdguardTeam/AdGuardHome@v0.107.43/client/node_modules/webpack/lib/NormalModule.js:323:13
    at /usr/ports/www/adguardhome/work/github.com/AdguardTeam/AdGuardHome@v0.107.43/client/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /usr/ports/www/adguardhome/work/github.com/AdguardTeam/AdGuardHome@v0.107.43/client/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/usr/ports/www/adguardhome/work/github.com/AdguardTeam/AdGuardHome@v0.107.43/client/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /usr/ports/www/adguardhome/work/github.com/AdguardTeam/AdGuardHome@v0.107.43/client/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v20.10.0
```

**Comment by yurivict** [comment]
Same happens with 0.107.42 for which it was possible to build the frontend before.
Something changed in the NodeJS world that causes this failure.

**Comment by RonKhondji** [comment]
Building works with Node v16.20.2
Anything newer than that fails.

**Comment by schzhn** [comment]
You can fix this by either using the older version of Node.js or by using the `--openssl-legacy-provider option`.
```
export NODE_OPTIONS=--openssl-legacy-provider
```

**Comment by yurivict** [comment]
@RonKhondji  @schzhn 

It fails the same way with node-16.20.1

Relevant NodeJS packages that are installed:
```
node16-16.20.1_3               V8 JavaScript for client and server
npm-node16-9.9.0               Node package manager
yarn-node16-1.22.19            Package manager for node, alternative to npm
```

**Comment by ainar-g** [comment]
@schzhn, let's document that as a new subsection within the `#building` section of the README.
